spring.application.name=service

# Initialize the database with the schema file created earlier
spring.sql.init.mode=always

spring.datasource.url=jdbc:postgresql://localhost/database
spring.datasource.username=user
spring.datasource.password=secret

spring.aot.repositories.enabled=false
